name: hyshare
description:

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  # Model View Controller Plugin
  get: ^4.6.5

  # Local Database
  shared_preferences: ^2.0.15
  get_storage: ^2.0.3
  hive: ^2.2.3

  # Image File
  flutter_svg: ^2.0.10+1
  lottie: ^3.1.2

  # Security
  crypto: ^3.0.2

  # Json
  json_serializable: ^6.3.0
  build_runner: ^2.1.11

  # Lints
  flutter_lints: ^4.0.0

  # Ready to Build App
  flutter_native_splash: ^2.2.4
  flutter_launcher_icons: ^0.13.1

  #
  google_sign_in: ^6.2.1

  # HTTP
  dio: ^5.5.0+1
  jwt_decoder: ^2.0.1

  # Native Widget
  fluttertoast: ^8.0.9

  # Good Widget
  shimmer: ^3.0.0
  flutter_keyboard_visibility: ^6.0.0

  # Util
  intl: ^0.19.0
  uuid: ^4.4.0
  permission_handler: ^11.3.1
  flutter_secure_storage: ^9.2.2
  upgrader: ^10.3.0
  in_app_review: ^2.0.8
  connectivity_plus: ^6.0.3
  awesome_notifications: ^0.9.3+1

  path_provider: ^2.1.3

  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.3
  flutter_expandable_fab: ^2.3.0
  firebase_auth: ^5.3.1
  firebase_messaging: ^15.1.3
  firebase_analytics: ^11.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lotties/

  fonts:
    - family: Pretendard
      fonts:
        - asset: fonts/Pretendard/Pretendard-Thin.ttf
          weight: 100
        - asset: fonts/Pretendard/Pretendard-ExtraLight.ttf
          weight: 200
        - asset: fonts/Pretendard/Pretendard-Light.ttf
          weight: 300
        - asset: fonts/Pretendard/Pretendard-Regular.ttf
          weight: 400
        - asset: fonts/Pretendard/Pretendard-Medium.ttf
          weight: 500
        - asset: fonts/Pretendard/Pretendard-SemiBold.ttf
          weight: 600
        - asset: fonts/Pretendard/Pretendard-Bold.ttf
          weight: 700
        - asset: fonts/Pretendard/Pretendard-ExtraBold.ttf
          weight: 800
        - asset: fonts/Pretendard/Pretendard-Black.ttf
          weight: 900
