// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEuG5MxjRr4x6Qj5VdJiTEv5yRNi5MJRk',
    appId: '1:518305719894:web:ed00755f0dfe40449dfdf7',
    messagingSenderId: '518305719894',
    projectId: 'hyshare-bba6c',
    authDomain: 'hyshare-bba6c.firebaseapp.com',
    storageBucket: 'hyshare-bba6c.appspot.com',
    measurementId: 'G-MS9CN6GEQL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4vGhW-y_v24tAHZPRYVWx7fE6kj48_sY',
    appId: '1:518305719894:android:e29ad2fc85601b359dfdf7',
    messagingSenderId: '518305719894',
    projectId: 'hyshare-bba6c',
    storageBucket: 'hyshare-bba6c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC18XymFYZXIhkM3Rj332zl5DOy_0inHnw',
    appId: '1:518305719894:ios:222c99f9eab234029dfdf7',
    messagingSenderId: '518305719894',
    projectId: 'hyshare-bba6c',
    storageBucket: 'hyshare-bba6c.appspot.com',
    iosBundleId: 'com.erica.hyshare',
  );
}
